/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.currencyconverter;

import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.time.format.DateTimeFormatterBuilder;
import java.util.Scanner;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Tristan
 */
public class MainFrame extends javax.swing.JFrame {
    
    static double[] currentRates = new double[11];
    static double[] prevRates = new double[11];
    static double[] rateChange = new double[11];
    
    Connection conn = null;
    PreparedStatement preparedStatement = null;
    ResultSet resultSet = null;

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //connect to database class
        conn = DBConnectionClass.connectionDB();
        
        //get rates from the api
        apiCall();
        
        //get the difference of the current rate and the previous rate
        getDifference();
        
        //assign previous rates to swing label
        prev_usd_php.setText(prevRates[0] + "");
        prev_yen_php.setText(prevRates[1] + "");
        prev_gbp_php.setText(prevRates[2] + "");
        prev_hkd_php.setText(prevRates[3] + "");
        prev_chf_php.setText(prevRates[4] + "");
        prev_cad_php.setText(prevRates[5] + "");
        prev_sgd_php.setText(prevRates[6] + "");
        prev_aud_php.setText(prevRates[7] + "");
        prev_bhd_php.setText(prevRates[8] + "");
        prev_kwd_php.setText(prevRates[9] + "");
        prev_sar_php.setText(prevRates[10] + "");

        //assign current rates to swing label
        current_usd_php.setText(currentRates[0] + "");
        current_yen_php.setText(currentRates[1] + "");
        current_gbp_php.setText(currentRates[2] + "");
        current_hkd_php.setText(currentRates[3] + "");
        current_chf_php.setText(currentRates[4] + "");
        current_cad_php.setText(currentRates[5] + "");
        current_sgd_php.setText(currentRates[6] + "");
        current_aud_php.setText(currentRates[7] + "");
        current_bhd_php.setText(currentRates[8] + "");
        current_kwd_php.setText(currentRates[9] + "");
        current_sar_php.setText(currentRates[10] + "");
        
        //assign the movement to the gui frontend
        movement_usd_php.setText(getMovement(rateChange[0]));
        movement_yen_php.setText(getMovement(rateChange[1]));
        movement_gbp_php.setText(getMovement(rateChange[2]));
        movement_hkd_php.setText(getMovement(rateChange[3]));
        movement_chf_php.setText(getMovement(rateChange[4]));
        movement_cad_php.setText(getMovement(rateChange[5]));
        movement_sgd_php.setText(getMovement(rateChange[6]));
        movement_aud_php.setText(getMovement(rateChange[7]));
        movement_bhd_php.setText(getMovement(rateChange[8]));
        movement_kwd_php.setText(getMovement(rateChange[9]));
        movement_sar_php.setText(getMovement(rateChange[10]));
        
        //save today's current exchange to database
        saveRate();
        //close the connection to database;
        try {
            conn.close();
        } catch (Exception e) {
            System.out.println("Unable to close connection to databse" + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        prev_usd_php = new javax.swing.JLabel();
        prev_yen_php = new javax.swing.JLabel();
        prev_gbp_php = new javax.swing.JLabel();
        prev_hkd_php = new javax.swing.JLabel();
        prev_chf_php = new javax.swing.JLabel();
        prev_cad_php = new javax.swing.JLabel();
        prev_aud_php = new javax.swing.JLabel();
        prev_sgd_php = new javax.swing.JLabel();
        prev_bhd_php = new javax.swing.JLabel();
        prev_kwd_php = new javax.swing.JLabel();
        prev_sar_php = new javax.swing.JLabel();
        current_yen_php = new javax.swing.JLabel();
        current_usd_php = new javax.swing.JLabel();
        current_gbp_php = new javax.swing.JLabel();
        current_hkd_php = new javax.swing.JLabel();
        current_chf_php = new javax.swing.JLabel();
        current_cad_php = new javax.swing.JLabel();
        current_sgd_php = new javax.swing.JLabel();
        current_aud_php = new javax.swing.JLabel();
        current_bhd_php = new javax.swing.JLabel();
        current_kwd_php = new javax.swing.JLabel();
        current_sar_php = new javax.swing.JLabel();
        movement_yen_php = new javax.swing.JLabel();
        movement_usd_php = new javax.swing.JLabel();
        movement_gbp_php = new javax.swing.JLabel();
        movement_hkd_php = new javax.swing.JLabel();
        movement_chf_php = new javax.swing.JLabel();
        movement_cad_php = new javax.swing.JLabel();
        movement_sgd_php = new javax.swing.JLabel();
        movement_aud_php = new javax.swing.JLabel();
        movement_bhd_php = new javax.swing.JLabel();
        movement_kwd_php = new javax.swing.JLabel();
        movement_sar_php = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(25, 26, 25));

        jPanel2.setBackground(new java.awt.Color(30, 81, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(25, 26, 25));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(30, 81, 40), new java.awt.Color(30, 81, 40), new java.awt.Color(30, 81, 40), new java.awt.Color(30, 81, 40)));

        jLabel1.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(78, 159, 61));
        jLabel1.setText("Previous Rate:");

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(78, 159, 61));
        jLabel2.setText("Current Rate:");

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(78, 159, 61));
        jLabel3.setText("Movement:");

        jLabel4.setFont(new java.awt.Font("Dialog", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(78, 159, 61));
        jLabel4.setText("Currency:");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(78, 159, 61));
        jLabel5.setText("USD to PHP:");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(78, 159, 61));
        jLabel6.setText("YEN to PHP:");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(78, 159, 61));
        jLabel7.setText("GBP to PHP:");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(78, 159, 61));
        jLabel8.setText("HKD  to PHP:");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(78, 159, 61));
        jLabel9.setText("CHF to PHP:");

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(78, 159, 61));
        jLabel10.setText("SGD to PHP:");

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(78, 159, 61));
        jLabel11.setText("CAD to PHP:");

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(78, 159, 61));
        jLabel12.setText("AUD to PHP:");

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(78, 159, 61));
        jLabel13.setText("KWD to PHP:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(78, 159, 61));
        jLabel14.setText("BHD to PHP:");

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(78, 159, 61));
        jLabel15.setText("SAR to PHP:");

        prev_usd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_usd_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_usd_php.setText("0.00");
        prev_usd_php.setName("prev_usd_php"); // NOI18N

        prev_yen_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_yen_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_yen_php.setText("0.00");
        prev_yen_php.setName("prev_yen_php"); // NOI18N

        prev_gbp_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_gbp_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_gbp_php.setText("0.00");
        prev_gbp_php.setName("prev_gbp_php"); // NOI18N

        prev_hkd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_hkd_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_hkd_php.setText("0.00");
        prev_hkd_php.setName("prev_hkd_php"); // NOI18N

        prev_chf_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_chf_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_chf_php.setText("0.00");
        prev_chf_php.setName("prev_chf_php"); // NOI18N

        prev_cad_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_cad_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_cad_php.setText("0.00");
        prev_cad_php.setName("prev_cad_php"); // NOI18N

        prev_aud_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_aud_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_aud_php.setText("0.00");
        prev_aud_php.setName("prev_aud_php"); // NOI18N

        prev_sgd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_sgd_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_sgd_php.setText("0.00");
        prev_sgd_php.setName("prev_sgd_php"); // NOI18N

        prev_bhd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_bhd_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_bhd_php.setText("0.00");
        prev_bhd_php.setName("prev_bhd_php"); // NOI18N

        prev_kwd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_kwd_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_kwd_php.setText("0.00");
        prev_kwd_php.setName("prev_kwd_php"); // NOI18N

        prev_sar_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        prev_sar_php.setForeground(new java.awt.Color(78, 159, 61));
        prev_sar_php.setText("0.00");
        prev_sar_php.setName("prev_sar_php"); // NOI18N

        current_yen_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_yen_php.setForeground(new java.awt.Color(78, 159, 61));
        current_yen_php.setText("0.00");
        current_yen_php.setName("current_yen_php"); // NOI18N

        current_usd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_usd_php.setForeground(new java.awt.Color(78, 159, 61));
        current_usd_php.setText("0.00");
        current_usd_php.setName("current_usd_php"); // NOI18N

        current_gbp_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_gbp_php.setForeground(new java.awt.Color(78, 159, 61));
        current_gbp_php.setText("0.00");
        current_gbp_php.setName("current_gbp_php"); // NOI18N

        current_hkd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_hkd_php.setForeground(new java.awt.Color(78, 159, 61));
        current_hkd_php.setText("0.00");
        current_hkd_php.setName("current_hkd_php"); // NOI18N

        current_chf_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_chf_php.setForeground(new java.awt.Color(78, 159, 61));
        current_chf_php.setText("0.00");
        current_chf_php.setName("current_chf_php"); // NOI18N

        current_cad_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_cad_php.setForeground(new java.awt.Color(78, 159, 61));
        current_cad_php.setText("0.00");
        current_cad_php.setName("current_cad_php"); // NOI18N

        current_sgd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_sgd_php.setForeground(new java.awt.Color(78, 159, 61));
        current_sgd_php.setText("0.00");
        current_sgd_php.setName("current_sgd_php"); // NOI18N

        current_aud_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_aud_php.setForeground(new java.awt.Color(78, 159, 61));
        current_aud_php.setText("0.00");
        current_aud_php.setName("current_aud_php"); // NOI18N

        current_bhd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_bhd_php.setForeground(new java.awt.Color(78, 159, 61));
        current_bhd_php.setText("0.00");
        current_bhd_php.setName("current_bhd_php"); // NOI18N

        current_kwd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_kwd_php.setForeground(new java.awt.Color(78, 159, 61));
        current_kwd_php.setText("0.00");
        current_kwd_php.setName("current_kwd_php"); // NOI18N

        current_sar_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        current_sar_php.setForeground(new java.awt.Color(78, 159, 61));
        current_sar_php.setText("0.00");
        current_sar_php.setName("current_sar_php"); // NOI18N

        movement_yen_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_yen_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_yen_php.setText("0.00");
        movement_yen_php.setName("movement_yen_php"); // NOI18N

        movement_usd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_usd_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_usd_php.setText("0.00");
        movement_usd_php.setName("movement_usd_php"); // NOI18N

        movement_gbp_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_gbp_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_gbp_php.setText("0.00");
        movement_gbp_php.setName("movement_gbp_php"); // NOI18N

        movement_hkd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_hkd_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_hkd_php.setText("0.00");
        movement_hkd_php.setName("movement_hkd_php"); // NOI18N

        movement_chf_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_chf_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_chf_php.setText("0.00");
        movement_chf_php.setName("movement_chf_php"); // NOI18N

        movement_cad_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_cad_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_cad_php.setText("0.00");
        movement_cad_php.setName("movement_cad_php"); // NOI18N

        movement_sgd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_sgd_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_sgd_php.setText("0.00");
        movement_sgd_php.setName("movement_sgd_php"); // NOI18N

        movement_aud_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_aud_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_aud_php.setText("0.00");
        movement_aud_php.setName("movement_aud_php"); // NOI18N

        movement_bhd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_bhd_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_bhd_php.setText("0.00");
        movement_bhd_php.setName("movement_bhd_php"); // NOI18N

        movement_kwd_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_kwd_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_kwd_php.setText("0.00");
        movement_kwd_php.setName("movement_kwd_php"); // NOI18N

        movement_sar_php.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        movement_sar_php.setForeground(new java.awt.Color(78, 159, 61));
        movement_sar_php.setText("0.00");
        movement_sar_php.setName("movement_sar_php"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13)
                            .addComponent(jLabel15))
                        .addGap(116, 116, 116)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(prev_usd_php, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(prev_yen_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_gbp_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_hkd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_chf_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_cad_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_sgd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_aud_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_bhd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_kwd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prev_sar_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(114, 114, 114)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(current_usd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_yen_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_gbp_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_hkd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_chf_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_cad_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_sgd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_aud_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_bhd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_kwd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(current_sar_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1)
                        .addGap(75, 75, 75)
                        .addComponent(jLabel2)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movement_usd_php, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movement_yen_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_gbp_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_hkd_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_chf_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_cad_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_sgd_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_aud_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_bhd_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_kwd_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movement_sar_php, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 12, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(44, 44, 44))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(prev_usd_php)
                    .addComponent(current_usd_php)
                    .addComponent(movement_usd_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(prev_yen_php)
                    .addComponent(current_yen_php)
                    .addComponent(movement_yen_php))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(prev_gbp_php)
                    .addComponent(current_gbp_php)
                    .addComponent(movement_gbp_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(prev_hkd_php)
                    .addComponent(current_hkd_php)
                    .addComponent(movement_hkd_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(prev_chf_php)
                    .addComponent(current_chf_php)
                    .addComponent(movement_chf_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(prev_cad_php)
                    .addComponent(current_cad_php)
                    .addComponent(movement_cad_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(prev_sgd_php)
                    .addComponent(current_sgd_php)
                    .addComponent(movement_sgd_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(prev_aud_php)
                    .addComponent(current_aud_php)
                    .addComponent(movement_aud_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(prev_bhd_php)
                    .addComponent(current_bhd_php)
                    .addComponent(movement_bhd_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(prev_kwd_php)
                    .addComponent(current_kwd_php)
                    .addComponent(movement_kwd_php))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(prev_sar_php)
                    .addComponent(current_sar_php)
                    .addComponent(movement_sar_php))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
        
        new LoadingFrame().dispose();
    }

        //get api here
    
   static void apiCall(){
        
        String[] currencies = {"USD","JPY","GBP","HKD","CHF","CAD","SGD","AUD","BHD","KWD","SAR"};
        
            
            //get current rates from the api
        
           for(int i = 0; i < currentRates.length; i++){
               currentRates[i] = getUpdatedRate(currencies[i]);
           }
           
           //get the previouse rates from the api
           for(int i = 0; i < prevRates.length; i++){
               prevRates[i] = getPreviousRate(currencies[i]);
           }
    }
    
    static double getUpdatedRate(String currency){
        
        try {
           double rate;
           
            URL apiUrl = new URL("https://free.currconv.com/api/v7/convert?q=" + currency + "_PHP&compact=ultra&apiKey=5ffb75618801e0556531");
            HttpURLConnection conn = (HttpURLConnection) apiUrl.openConnection();
            conn.setRequestMethod("GET");
            conn.connect();
            
            //check if response code is 200
            int responseCode = conn.getResponseCode();
            if(responseCode != 200){
                throw new RuntimeException("HttpResponseCode: "+ responseCode);
            } else {
                StringBuilder infoString = new StringBuilder();
                Scanner scanner = new Scanner(apiUrl.openStream());
                
                while(scanner.hasNext()){
                    infoString.append(scanner.nextLine());
                }
                scanner.close();
                
                System.out.println(infoString);
                
                //setup JSON-Simple
                JSONParser parser = new JSONParser();
                JSONObject jsonobject = (JSONObject) parser.parse(String.valueOf(infoString));
                
                rate = (double) jsonobject.get(currency + "_PHP");
                return rate;
            }
        } catch (Exception e) {
            System.out.println(e);
            return 0;
        }
    }
    
    static double getPreviousRate(String currency){
    
        try {
            double rate;
            DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
            LocalDate currentDate = LocalDate.now().minusDays(1);
            
            URL apiUrl = new URL("https://free.currconv.com/api/v7/convert?q="+currency+"_PHP&compact=ultra&date="+dtf.format(currentDate)+"&apiKey=5ffb75618801e0556531");
            HttpURLConnection conn = (HttpURLConnection) apiUrl.openConnection();
            conn.setRequestMethod("GET");
            conn.connect();
            
//            System.out.println(apiUrl);
            
            int responseCode = conn.getResponseCode();
            if(responseCode != 200){
                throw new RuntimeException("HTTPResponseCode" + responseCode);
            } else {
                StringBuilder infoString = new StringBuilder();
                Scanner scanner =  new Scanner(apiUrl.openStream());
                
                while(scanner.hasNext()){
                    infoString.append(scanner.nextLine());
                }
                
                scanner.close();    
                
                System.out.println(infoString);
                
                JSONParser parser = new JSONParser();
                JSONObject firstBbject = (JSONObject) parser.parse(String.valueOf(infoString));
                JSONObject secondObject = (JSONObject) parser.parse(String.valueOf(firstBbject.get(currency + "_PHP")));
               
                rate = (double) secondObject.get(dtf.format(currentDate));
                return rate;

            }
        } catch (Exception e) {
            System.out.println("Error in getting Updated rates:" + e);
            return 0;
        } 
    }
    
    static void getDifference(){
        for(int i = 0; i < rateChange.length; i++){
            rateChange[i] = currentRates[i] - prevRates[i];
        }
    }
    
    static String getMovement(double difference){
        String movement;
        
        if(difference == 0){
            return movement = "NO MOVEMENT";
        } else if (difference > 0){
            return movement = "UPWARD";
        }
        else {
            return movement = "DOWNWARD";
        }
    }

    public final void saveRate(){
        
        DateTimeFormatter dft = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDate currentDate = LocalDate.now();
    
        try {
            String query = "INSERT INTO currencylog VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?);";
        
            preparedStatement = conn.prepareStatement(query);
            preparedStatement.setDouble(1, currentRates[0]);
            preparedStatement.setDouble(2, currentRates[1]);
            preparedStatement.setDouble(3, currentRates[2]);
            preparedStatement.setDouble(4, currentRates[3]);
            preparedStatement.setDouble(5, currentRates[4]);
            preparedStatement.setDouble(6, currentRates[5]);
            preparedStatement.setDouble(7, currentRates[6]);
            preparedStatement.setDouble(8, currentRates[7]);
            preparedStatement.setDouble(9, currentRates[8]);
            preparedStatement.setDouble(10, currentRates[9]);
            preparedStatement.setDouble(11, currentRates[10]);
            preparedStatement.setDouble(12, rateChange[0]);
            preparedStatement.setDouble(13, rateChange[1]);
            preparedStatement.setDouble(14, rateChange[2]);
            preparedStatement.setDouble(15, rateChange[3]);
            preparedStatement.setDouble(16, rateChange[4]);
            preparedStatement.setDouble(17, rateChange[5]);
            preparedStatement.setDouble(18, rateChange[6]);
            preparedStatement.setDouble(19, rateChange[7]);
            preparedStatement.setDouble(20, rateChange[8]);
            preparedStatement.setDouble(21, rateChange[9]);
            preparedStatement.setDouble(22, rateChange[10]);
            preparedStatement.setString(23, dft.format(currentDate));
            
            preparedStatement.execute();
            
            System.out.println("Successfully saved into database");
        } catch (Exception e) {
            System.out.println("Error in saving into database: " + e);
        } finally{
            try {
                preparedStatement.close();
            } catch (Exception e) {
                System.out.println("Error in closing prepared statement: "+ e);
            }
        }
        
        
    }


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel current_aud_php;
    private javax.swing.JLabel current_bhd_php;
    private javax.swing.JLabel current_cad_php;
    private javax.swing.JLabel current_chf_php;
    private javax.swing.JLabel current_gbp_php;
    private javax.swing.JLabel current_hkd_php;
    private javax.swing.JLabel current_kwd_php;
    private javax.swing.JLabel current_sar_php;
    private javax.swing.JLabel current_sgd_php;
    private javax.swing.JLabel current_usd_php;
    private javax.swing.JLabel current_yen_php;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel movement_aud_php;
    private javax.swing.JLabel movement_bhd_php;
    private javax.swing.JLabel movement_cad_php;
    private javax.swing.JLabel movement_chf_php;
    private javax.swing.JLabel movement_gbp_php;
    private javax.swing.JLabel movement_hkd_php;
    private javax.swing.JLabel movement_kwd_php;
    private javax.swing.JLabel movement_sar_php;
    private javax.swing.JLabel movement_sgd_php;
    private javax.swing.JLabel movement_usd_php;
    private javax.swing.JLabel movement_yen_php;
    private javax.swing.JLabel prev_aud_php;
    private javax.swing.JLabel prev_bhd_php;
    private javax.swing.JLabel prev_cad_php;
    private javax.swing.JLabel prev_chf_php;
    private javax.swing.JLabel prev_gbp_php;
    private javax.swing.JLabel prev_hkd_php;
    private javax.swing.JLabel prev_kwd_php;
    private javax.swing.JLabel prev_sar_php;
    private javax.swing.JLabel prev_sgd_php;
    private javax.swing.JLabel prev_usd_php;
    private javax.swing.JLabel prev_yen_php;
    // End of variables declaration//GEN-END:variables
}
